### ISSUE TITLE
Request: support Markdown in copyright and update label

### ISSUE THREAD

**Issue by panathea** [zq99299/gitbook-plugin-page-footer-ex#2]
It would be nice if the plugin surrounded the copyright and update label in a [Markdown block](https://toolchain.gitbook.com/templating/builtin.html) for the purpose of adding bold, links, etc.

**Comment by zq99299** [comment]
add link? Bold font?

**Comment by panathea** [comment]
Example:

```
{
 "pluginsConfig": {	   
		"page-footer-ex":{
			"copyright":"[mrcode](https://github.com/zq99299)",
			"update_label":"**updated** on",
			"update_format":"YYYY-MM-DD HH:mm:ss",
		}	   
  }	
}
```

**Comment by zq99299** [comment]
Well, well, I understand that I am studying how this formatted into markdown, i was a java development engineer, weak on the front end, and if you would, you could submit an update

**Comment by panathea** [comment]
Sure thing, it shouldn't be a large change.

**Comment by zq99299** [comment]
Let me think about how to distinguish between html code and markdown code, then stay at the entrance is that you can write html code

**Comment by panathea** [comment]
Oh, for some reason it didn't click that you could use html directly. Maybe a flag could be used to distinguish?

```json
{
  "pluginsConfig": {
    "page-footer-ex": {
      "markdown": false,
      "copyright": "<i>mrcode</i>",
      "update_label": "updated on",
      "update_format": "YYYY-MM-DD HH:mm:ss"
    }
  }
}
```

**Comment by zq99299** [comment]
Thank you very much, then how to analyze the remaining markdown, and free time to update the problem

**Comment by zq99299** [comment]
@morinted 

There is an error in the following page:
https://zq99299.gitbooks.io/gitbook-guide/content/chapter/plugin/navigator.html
https://zq99299.gitbooks.io/gitbook-guide/content/chapter/plugin/prismjs.html
https://zq99299.gitbooks.io/gitbook-guide/content/chapter/dev_plugin.html

Above the performance. I found that the asynchronous markdown parser will affect the original parsing of gitbook.

You have the words and then put this solution under it. I have been working a little bit recently and have no time to study these

This is the github address of this book ： https://github.com/zq99299/gitbook-guide

**Comment by panathea** [comment]
Okay, I will investigate, thank you.

**Comment by zq99299** [comment]
@morinted 

This is terrible, you take a closer look at the generated html code, will seriously affect the original md file, gitbook on the next page of the functional style has been affected.

I think the problem may be the use of his parser for the sake of it We add this plug-in html to be added to the end of the page, or seemingly have problems

Wrong or just that few pages. I use the gitbook serve locally to preview the effect

**Comment by panathea** [comment]
I will pull https://github.com/zq99299/gitbook-guide and develop against it.

**Comment by zq99299** [comment]
英文不是我的强项，你还是自己翻译好了。我怕我翻译的你看不懂：

嗯。你的思路很厉害。问题可能就出在这个markdown的解析上了。

我查看了每个生成html后的页面，发现他们的插入位置，都不是在 文件的末尾。或许就是因为这个原因，破坏了他们原有的html代码结构。

**Comment by panathea** [comment]
I think the problem is that the HTML is getting parsed by Gitbook as Markdown. I am investigating how to fix it.

**Comment by zq99299** [comment]
加油，辛苦你了。 最近我的工作太多了。

**Comment by panathea** [comment]
Okay, I think the solution is to render to HTML and keep it all in one line...

<img width="1254" alt="screen shot 2017-09-07 at 10 53 50 pm" src="https://user-images.githubusercontent.com/5840970/30194176-911dc13e-941f-11e7-8893-98ee1f5bfe41.png">

**Comment by zq99299** [comment]
@morinted 

```
# 插件开发

## 官方文档参考
- 模版变量 

大部分页面替换定制显示类容都可以使用该方式，可以获取到内置的一些信息
https://toolchain.gitbook.com/templating/variables.html

- 如何开发插件

https://toolchain.gitbook.com/plugins/
最简答的办法就是先看官方文档，了解一个大概，再去去看一款比较简单的源码。模仿人家写。

> 自己开发的插件链接存档，方便调试：由于npm link 不支持windows。所以使用该方法

- "anchor-navigation-ex@git+https://github.com/zq99299/gitbook-plugin-anchor-navigation-ex.git",
- "page-footer-ex@git+https://github.com/zq99299/gitbook-plugin-page-footer-ex.git"
````

在这种markdown结尾的，我们的插件生成的代码 不在正确的地方。造成样式有问题

这是效果。尾部生成的代码被嵌入进去了
https://zq99299.gitbooks.io/gitbook-guide/content/chapter/dev_plugin.html

**Comment by zq99299** [comment]
如果有办法 将生成的插件代码 不放在内容区域 就好了。那样就不会破坏原有的结构和内容

**Comment by panathea** [comment]
This is a simple regression -- my bad 😅 

```diff
diff --git a/assets/lib/plugin.js b/assets/lib/plugin.js
index 20b6aea..b09df3c 100644
--- a/assets/lib/plugin.js
+++ b/assets/lib/plugin.js
@@ -17,7 +17,7 @@ module.exports = function(book, page) {
         .then(function(labels) {
             var copyright = labels[0];
             var updateLabel = labels[1];
-            page.content += [
+            page.content += '\n\n' + [
                 '<footer class="page-footer-ex">',
                     '<div class="page-footer-ex-copyright">',
                         copyright,
```

**Comment by zq99299** [comment]
有其他的 markdown解析器吗，用来解析一下，再用之前的方法 添加到页面尾部。就解决了

**Comment by panathea** [comment]
I don't understand.

Does #6 fix?

**Comment by zq99299** [comment]
好的。 问题暂时解决了。 以后发现问题再说吧。 下午 我发布到 npm

**Comment by panathea** [comment]
Thank you for your patience

Sorry for the problems!

**Comment by zq99299** [comment]
更新到v0.1.0， 如果后续有使用上的问题，再修复
Update to v0.1.0, if the follow-up on the use of the problem, and then repair
